/* global Zotero, IOUtils, PathUtils, SSStore, SSIndexer, SSPassages, setInterval, clearInterval */
/* exported SSOcr */

/**
 * OCR of PDFs excluded because they have no text layer, with ocrmypdf.
 *
 * A small shell script is written to the profile directory and opened in the
 * system's default terminal. It OCRs the PDF into a temporary file and, when
 * done, atomically replaces the original file (same folder, same name, so the
 * Zotero attachment keeps pointing at it). The plugin watches the file and,
 * once it changes, re-includes and re-indexes the document. Pending OCR jobs
 * survive a Zotero restart.
 */
var SSOcr = {
	POLL_MS: 5000,
	MAX_AGE_MS: 24 * 60 * 60 * 1000,
	_pending: new Map(), // key -> {itemID, path, mtime, size, started}
	_timer: null,
	_listeners: new Set(),

	get scriptDir() {
		return PathUtils.join(Zotero.Profile.dir, 'semantic-search', 'ocr');
	},

	get languages() {
		let v = String(Zotero.Prefs.get('extensions.semantic-search.ocr.languages', true) || '').trim();
		return /^[a-z_+]+$/i.test(v) ? v : 'ita+eng';
	},

	onChange(fn) {
		this._listeners.add(fn);
		return () => this._listeners.delete(fn);
	},

	_emit() {
		for (let fn of this._listeners) {
			try {
				fn();
			}
			catch (e) {
				Zotero.logError(e);
			}
		}
	},

	isPending(key) {
		return this._pending.has(key);
	},

	async startup() {
		try {
			let saved = JSON.parse(await SSStore.getMeta('ocr_pending') || '{}');
			for (let [key, job] of Object.entries(saved)) {
				if (Date.now() - job.started < this.MAX_AGE_MS) this._pending.set(key, job);
			}
		}
		catch (e) {
			Zotero.logError(e);
		}
		if (this._pending.size) {
			// The OCR may have finished while Zotero was closed
			await this._poll();
			this._ensureTimer();
		}
	},

	shutdown() {
		if (this._timer) clearInterval(this._timer);
		this._timer = null;
	},

	async _save() {
		await SSStore.setMeta('ocr_pending', JSON.stringify(Object.fromEntries(this._pending)));
	},

	_ensureTimer() {
		if (this._timer || !this._pending.size) return;
		this._timer = setInterval(() => {
			this._poll().catch(e => Zotero.logError(e));
		}, this.POLL_MS);
	},

	_quote(s) {
		return "'" + String(s).replace(/'/g, "'\\''") + "'";
	},

	_messages() {
		let it = Zotero.locale.startsWith('it');
		return it
			? {
				missing: 'ocrmypdf non è installato. Installalo, ad esempio con: brew install ocrmypdf',
				done: 'OCR completato: Zotero reindicizzerà il documento. Puoi chiudere questa finestra.',
				failed: 'OCR non riuscito: il file originale non è stato modificato.',
				press: 'Premi Invio per chiudere...',
			}
			: {
				missing: 'ocrmypdf is not installed. Install it, e.g. with: brew install ocrmypdf',
				done: 'OCR finished: Zotero will re-index the document. You can close this window.',
				failed: 'OCR failed: the original file was not modified.',
				press: 'Press Enter to close...',
			};
	},

	/** Bash script (macOS / Linux) */
	_shellScript(path, key) {
		let m = this._messages();
		return `#!/bin/bash
# Generated by Zotero Semantic Search: OCR of one PDF with ocrmypdf
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
IN=${this._quote(path)}
WANTED=${this._quote(this.languages)}
DIR="$(dirname "$IN")"
echo "Semantic Search – OCR"
echo "$IN"
echo
if ! command -v ocrmypdf >/dev/null 2>&1; then
	echo ${this._quote(m.missing)}
	read -r -p ${this._quote(m.press)} _
	exit 1
fi
AVAILABLE="$(tesseract --list-langs 2>/dev/null)"
LANGS=""
IFS='+' read -ra WANT <<< "$WANTED"
for l in "\${WANT[@]}"; do
	if echo "$AVAILABLE" | grep -qx "$l"; then LANGS="\${LANGS:+$LANGS+}$l"; fi
done
[ -z "$LANGS" ] && LANGS=eng
EXTRA=()
if echo "$AVAILABLE" | grep -qx osd; then EXTRA+=(--rotate-pages); fi
TMP="$(mktemp -d)"
# --force-ocr: the PDF has (almost) no text; --skip-text would skip every page
# that carries even a watermark, so all pages are OCRed
if ocrmypdf --force-ocr --output-type pdf "\${EXTRA[@]}" -l "$LANGS" "$IN" "$TMP/ocr.pdf"; then
	# copy next to the original, then rename over it (atomic replace, same name)
	cp "$TMP/ocr.pdf" "$DIR/.ocr-${key}.tmp" && mv -f "$DIR/.ocr-${key}.tmp" "$IN"
	rm -rf "$TMP"
	echo
	echo ${this._quote(m.done)}
else
	rm -rf "$TMP"
	echo
	echo ${this._quote(m.failed)}
	read -r -p ${this._quote(m.press)} _
	exit 1
fi
`;
	},

	/** Batch script (Windows) */
	_cmdScript(path, key) {
		let m = this._messages();
		let q = s => '"' + String(s).replace(/"/g, '') + '"';
		let tmp = `%TEMP%\\semantic-search-ocr-${key}.pdf`;
		return `@echo off\r
chcp 65001 >nul\r
echo Semantic Search - OCR\r
echo ${path}\r
where ocrmypdf >nul 2>nul || (echo ${m.missing} & pause & exit /b 1)\r
ocrmypdf --force-ocr --output-type pdf -l ${this.languages} ${q(path)} "${tmp}" || (echo ${m.failed} & pause & exit /b 1)\r
move /Y "${tmp}" ${q(path)} >nul || (echo ${m.failed} & pause & exit /b 1)\r
echo ${m.done}\r
pause\r
`;
	},

	/** Launch OCR of an attachment in the default terminal */
	async start(item) {
		if (!item || !item.isPDFAttachment()) throw new Error('Not a PDF attachment');
		let path = await item.getFilePathAsync();
		if (!path) throw new Error('The PDF file is not available on this computer');
		let info = await IOUtils.stat(path);
		await IOUtils.makeDirectory(this.scriptDir, { createAncestors: true, ignoreExisting: true });
		if (Zotero.isWin) {
			let script = PathUtils.join(this.scriptDir, `ocr-${item.key}.cmd`);
			await IOUtils.writeUTF8(script, this._cmdScript(path, item.key));
			Zotero.launchFile(script);
		}
		else {
			let script = PathUtils.join(this.scriptDir, `ocr-${item.key}.command`);
			await IOUtils.writeUTF8(script, this._shellScript(path, item.key));
			await IOUtils.setPermissions(script, 0o755);
			if (Zotero.isMac) {
				// `open` uses the default application for .command files (Terminal, iTerm…)
				await Zotero.Utilities.Internal.exec('/usr/bin/open', [script]);
			}
			else {
				let found = null;
				for (let t of ['/usr/bin/x-terminal-emulator', '/usr/bin/gnome-terminal', '/usr/bin/konsole', '/usr/bin/xterm']) {
					if (await IOUtils.exists(t)) {
						found = t;
						break;
					}
				}
				if (!found) throw new Error('No terminal emulator found');
				let args = found.endsWith('gnome-terminal') ? ['--', '/bin/bash', script] : ['-e', '/bin/bash ' + script];
				await Zotero.Utilities.Internal.exec(found, args);
			}
		}
		this._pending.set(item.key, {
			itemID: item.id,
			path,
			mtime: info.lastModified,
			size: info.size,
			started: Date.now(),
		});
		await this._save();
		this._ensureTimer();
		this._emit();
	},

	async _poll() {
		let changed = false;
		for (let [key, job] of [...this._pending]) {
			if (Date.now() - job.started > this.MAX_AGE_MS) {
				this._pending.delete(key);
				changed = true;
				continue;
			}
			let info;
			try {
				info = await IOUtils.stat(job.path);
			}
			catch (e) {
				continue; // being replaced right now
			}
			if (info.lastModified === job.mtime && info.size === job.size) continue;
			this._pending.delete(key);
			changed = true;
			await this._finished(key, job);
		}
		if (changed) {
			await this._save();
			this._emit();
		}
		if (!this._pending.size && this._timer) {
			clearInterval(this._timer);
			this._timer = null;
		}
	},

	/** The PDF was replaced by its OCRed version: refresh caches and re-index */
	async _finished(key, job) {
		try {
			SSPassages._fulltext.delete(key);
			await IOUtils.remove(PathUtils.join(SSPassages.textCacheDir, key + '.txt'), { ignoreAbsent: true });
			let item = await Zotero.Items.getAsync(job.itemID);
			if (!item) return;
			// Zotero's own full-text index (for its regular searches)
			try {
				await Zotero.FullText.indexItems([item.id], { complete: true, ignoreErrors: true });
			}
			catch (e) {
				Zotero.debug('Semantic Search: Zotero full-text re-index failed: ' + e);
			}
			await SSStore.removeExcluded(key);
			await SSIndexer.indexItems([item], { force: true });
		}
		catch (e) {
			Zotero.logError(e);
		}
	},
};
